### ISSUE TITLE
no github v0.4.3 release?

### ISSUE THREAD

**Issue by filippog** [urbanairship/tessera-client#5]
hi!
looks like tessera-client 0.4.3 is on pypi but not released on github ?

**Comment by aalpern** [comment]
I guess the tag just didn't get pushed. The current state of master is what's in pypi - this module has hardly any code velocity.

**Comment by filippog** [comment]
:+1: thanks! I guess it makes more sense to grab releases from pypi anyway

**Comment by aalpern** [comment]
Tagged it for posterity.
